### ISSUE TITLE
ModuleNotFoundError: No module named 'cairocffi' on Quivi 2.0.3

### ISSUE THREAD

**Issue by altieresrohr** [qazmlpok/quivi#7]
Hello,

First of all, I'm very glad to see someone is working on this program. This was the only image viewer fast enough for a Windows tablet I had.

Version 2.0.2 is working fine, but on 2.0.3 I'm getting errors on both standalone and installed versions, both with apparently the same error on Windows 11. It's apparently related to the added Cairo functionality.

This is the error I got from the installed version with local user installation:

> Traceback (most recent call last):
>   File "wx\lib\wxcairo\__init__.py", line 59, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "wx\lib\wxcairo\wx_cairocffi.py", line 34, in <module>
> ModuleNotFoundError: No module named 'cairocffi'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "quivi.pyw", line 67, in <module>
>   File "quivi.pyw", line 11, in run
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "quivilib\control\main.py", line 10, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "quivilib\model\__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "quivilib\model\container\__init__.py", line 2, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "quivilib\model\image\__init__.py", line 14, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "quivilib\model\image\cairo.py", line 7, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "wx\lib\wxcairo\__init__.py", line 64, in <module>
>   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "wx\lib\wxcairo\wx_pycairo.py", line 432, in <module>
>   File "wx\lib\wxcairo\wx_pycairo.py", line 192, in _findCairoLib
> RuntimeError: Unable to find the Cairo shared library

My system does have Python installed, but I don't think it should be interfering, unless I'm missing something.

Thanks!

**Comment by qazmlpok** [comment]
Looks like cairo.dll wasn't being included. It worked fine on my local machine because I have GIMP installed. Guess I should start testing with a VM.

Try this release. If it works I'll replace it with a proper release.

https://github.com/qazmlpok/quivi/releases/tag/quivi-test

**Comment by altieresrohr** [comment]
Yes, this one works for me. Copying cairo.dll from this release to the old one worked as well!

Thank you.

**Comment by altieresrohr** [comment]
By the way, it seems switching to a different language isn't working. The locale changes and the time/date format is updated, but the interface text isn't, even after a restart Do you want me to open a new issue for that, or is this a known issue because of the missing text?

**Comment by qazmlpok** [comment]
That should be a separate issue. The translations were done in the original 1.2 version of the application. All of the new stuff (mentioned in the readme) definitely won't be translated.

I honestly haven't touched the translations at all. I assume that the method of translation still works; this might just be another installer issue where it isn't picking up all the needed files.

**Comment by qazmlpok** [comment]
New release published, with the cairo dll. I'm pretty sure I fixed the localization issue too. If that's still broken, please open a new issue. There will be plenty of untranslated text, but all of the old stuff should show up now.
